const express =  require("express")
const mongoose =  require("mongoose")
const cors =  require("cors")
const app = express()
const bcrypt =require("bcryptjs")
const jwt =require("jsonwebtoken")
app.use(cors())
app.use(express.json())